/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721BurnableUpgradeable } from "./ERC721BurnableUpgradeable";
export type { ERC721EnumerableUpgradeable } from "./ERC721EnumerableUpgradeable";
export type { ERC721PausableUpgradeable } from "./ERC721PausableUpgradeable";
export type { ERC721URIStorageUpgradeable } from "./ERC721URIStorageUpgradeable";
export type { ERC721VotesUpgradeable } from "./ERC721VotesUpgradeable";
